### ISSUE TITLE
Issue with latest version of `strawberry` 0.115.0

### ISSUE THREAD

**Issue by ammar-faifi** [nrbnlulu/strawberry-django-auth#10]
# Prerequisites

* [x] Is it a bug?
* [ ] Is it a new feature?
* [ ] Is it a a question?
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/nrbnlulu/strawberry-django-auth/blob/master/CONTRIBUTING.md) guide.

# Description

Description of the bug/feature/question

# Steps to Reproduce

upgrade to `strawberry-graphql==0.115.0`

## Expected behavior
no conflict 

the error
```
  File "/Volumes/SSD/projects/petroly/petroly-django/env3.10/lib/python3.10/site-packages/gqlauth/bases/mixins.py", line 195, in __init_subclass__
    for name, ret_type in parent_resolver.base_resolver.annotations.items():
AttributeError: 'StrawberryResolver' object has no attribute 'annotations'. Did you mean: '__annotations__'?

```

Paste the packages you are using, you can get this information from executing `pip freeze`.

**Comment by ammar-faifi** [comment]
we need temp modify the `setup.py`
https://github.com/nrbnlulu/strawberry-django-auth/blob/2c92b9f4285659854436c7b5059b50a650bc7d57/setup.py#L54

**Comment by nrbnlulu** [comment]
Hey, maybe a strawberry version check at that line will do as well.
I will look into it later today.

**Comment by nrbnlulu** [comment]
This will be fixed in a future release of strawberry https://github.com/strawberry-graphql/strawberry/issues/1989

**Comment by ammar-faifi** [comment]
fixed after https://github.com/strawberry-graphql/strawberry/releases/tag/0.116.2
