### ISSUE TITLE
Unknown field(s) (username) specified for myappUser

### ISSUE THREAD

**Issue by brentpicasso** [nrbnlulu/strawberry-django-auth#147]
# Prerequisites
*Feel free to just say what you want and remove this template.*

* [X] Is it a bug?
* [ ] Is it a new feature?
* [X] Is it a question?
* [X] Can you reproduce the problem?
* [X] Are you running the latest version?
* [X] Did you check for similar issues?
* [X] Did you perform a cursory search?

# Description
I am defining a custom user object that uses email as username. It appears that strawberry-django-auth is looking for a username property on my custom user object. 

``` File "/home/brent/myapp/myapp-api/myapp/schema.py", line 22, in <module>
    from gqlauth.user import arg_mutations as mutations
  File "/home/brent/.pyenv/versions/myapp-api/lib/python3.8/site-packages/gqlauth/user/arg_mutations.py", line 1, in <module>
    from gqlauth.core.mixins import ArgMixin
  File "/home/brent/.pyenv/versions/myapp-api/lib/python3.8/site-packages/gqlauth/core/mixins.py", line 9, in <module>
    from gqlauth.user.resolvers import BaseMixin
  File "/home/brent/.pyenv/versions/myapp-api/lib/python3.8/site-packages/gqlauth/user/resolvers.py", line 46, in <module>
    from gqlauth.user.forms import (
  File "/home/brent/.pyenv/versions/myapp-api/lib/python3.8/site-packages/gqlauth/user/forms.py", line 16, in <module>
    class RegisterForm(UserCreationForm):
  File "/home/brent/.pyenv/versions/myapp-api/lib/python3.8/site-packages/django/forms/models.py", line 276, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (username) specified for myappUser
```
Definition of my custom usr object - note how I have USERNAME_FIELD set to email

```class MyappUser(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True, max_length=254)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT)
    is_admin = models.BooleanField(default=False)

    objects = MyappUserManager()

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
```

Is it possible to specify a custom username field with the current strawberry-django-auth, or does this library need an enhancement? 

If the latter, any tips on what to change to support this? I'm happy to submit a PR. 

Thank you!

**Comment by nrbnlulu** [comment]
Hey, take a look at

https://github.com/nrbnlulu/strawberry-django-auth/blob/main/gqlauth/settings_type.py#L88

**Comment by brentpicasso** [comment]
Thank you, very much - that got me much further. 

I have another problem with the login mutation using email as username. 

I'm getting the error "User has no status." - raised by this code: https://github.com/nrbnlulu/strawberry-django-auth/blob/71c2dd54849ad2e81f6dc3c5bf2a6c8193a7834c/gqlauth/jwt/types_.py#L181

In your quickstart example I don't see the CustomUser model with the UserStatus field; how should I design my custom user model? is there a mixin I should use? 

Thanks again for your help!

**Comment by brentpicasso** [comment]
I figured it out;  we had existing users in our database; we needed to populate entries in the gqlauth_userstatus. 

Related, we needed to specify the email field throughout these settings:

```
from gqlauth.settings_type import email_field
GQL_AUTH = GqlAuthSettings(
    LOGIN_REQUIRE_CAPTCHA=False,
    REGISTER_REQUIRE_CAPTCHA=False,
    REGISTER_MUTATION_FIELDS=[email_field],
    LOGIN_FIELDS=[email_field],
    JWT_PAYLOAD_PK=email_field
)
```
