### ISSUE TITLE
"Expected Iterable, but did not find one for field" when using TokenRequired directive

### ISSUE THREAD

**Issue by brentpicasso** [nrbnlulu/strawberry-django-auth#158]
# Prerequisites

* [x] Is it a bug?
* [X] Is it a question?
* [X] Can you reproduce the problem?
* [X] Are you running the latest version?
* [X] Did you check for similar issues?
* [X] Did you perform a cursory search?

# Description

When I annotate the query in the way suggested in the tutorial, I get an error from graphql
```
strawberry.execution ERROR    Expected Iterable, but did not find one for field 'MyApiQuery.projects'.

GraphQL request:2:3
1 | query ProjectsSummaryQuery($statusFilter: String) {
2 |   projects(statusFilter: $statusFilter) {
  |   ^
3 |     id
```
=====my query code=====
```

from gqlauth.core.field_ import field

@strawberry.type
class NautilusApiQuery(UserQueries):

    @field(directives=[TokenRequired()])
    def projects(self, info: Info, status_filter: Optional[str] = None) -> List[ProjectType]:
        print("Getting projects")
        # ... do the query ...
        return queryset
```
Note: if I replace the @field with @strawberry.field,  I do not get this error.

**Comment by brentpicasso** [comment]
Interesting! I dug into the issue and I found there was an error decoding the token.   seems like the strawberry-django-auth decorator attempted to get the token, but the token was wrapped in b' <token> '    .

Assuming it was a byte array, I first tried to decode it, but this token was actually a string!

So I brought in the decorator locally to the function and hacked it to test my theory: 

```    @strawberry.field
    def projects(self, info: Info, status_filter: Optional[str] = None) -> List[ProjectType]:
    
        #######################################################################
        #### BRINGING IN THE @field(directives=[TokenRequired()]) LOCALLY#####
        #######################################################################
        from gqlauth.core.exceptions import TokenExpired
        from gqlauth.jwt.types_ import TokenType
        from jwt import PyJWTError
        from gqlauth.settings import gqlauth_settings as app_settings
        from gqlauth.core.types_ import GQLAuthError, GQLAuthErrors
        
        token = app_settings.JWT_TOKEN_FINDER(info)
        print("the token::: " + str(token))
        token = token[:-1]
        token = token[2:]
        print("the token after fixing ::: " + str(token))
        try:
            token_type = TokenType.from_token(token)
        except PyJWTError as pje:  # raised by python-jwt
            print("error " + str(pje))
            return GQLAuthError(code=GQLAuthErrors.INVALID_TOKEN)

        except TokenExpired:
            print("expired")
            return GQLAuthError(code=GQLAuthErrors.EXPIRED_TOKEN)
        user = token_type.get_user_instance()        
        
        print("user: " + str(user))        
        #######################################################################
        #######################################################################
        #######################################################################
        
        queryset = << do the query >>
        return queryset
```

Example: 
```
the token::: b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjoie1xuIFwiZW1haWxcIjogXCJyZWd1bGFydXNlckBuYXV0aWx1cy5iaW9cIixcbiBcImV4cFwiOiBcIjIwMjItMTAtMjBUMjM6MDI6NDAuMjQxMzQzXCIsXG4gXCJvcmlnSWF0XCI6IFwiMjAyMi0xMC0yMFQyMjo1Nzo0MC4yNDEzNDNcIlxufSJ9.Ar2mCAsNHM4GvLFBGZkQ9gkj_lpa99qsCWQ1zX9Ttcc'
the token after fixing ::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjoie1xuIFwiZW1haWxcIjogXCJyZWd1bGFydXNlckBuYXV0aWx1cy5iaW9cIixcbiBcImV4cFwiOiBcIjIwMjItMTAtMjBUMjM6MDI6NDAuMjQxMzQzXCIsXG4gXCJvcmlnSWF0XCI6IFwiMjAyMi0xMC0yMFQyMjo1Nzo0MC4yNDEzNDNcIlxufSJ9.Ar2mCAsNHM4GvLFBGZkQ9gkj_lpa99qsCWQ1zX9Ttcc
token: regularuser@myuser.com

```

**Comment by nrbnlulu** [comment]
`TokenRequired`  needs a union of your output type and `GQLAuthError` and because graphql specs won't allow lists in unions so you have an issue here..

**Comment by brentpicasso** [comment]
I've found that the token the client receives has the b'  ' embedded in the string.  

So I think it's related to what the server is sending to the client - I will investigate there.

**Comment by brentpicasso** [comment]
I found the root of the problem; it is in gqlauth/jwt/default_hooks.py.  The fix is to encode the jwt byte array into a string. 

This way, the token sent to the client will not have the b' ' wrapped around it. 

Around line 39:
```
                 payload={"payload": serialized},
                 key=cast(str, app_settings.JWT_SECRET_KEY),
                 algorithm=app_settings.JWT_ALGORITHM,
-            )
+            ).decode()
```

Should we submit a PR on this?

**Comment by nrbnlulu** [comment]
Hey, You can :upside_down_face:  though I had no issues with that, I'll take a closer look later this week hopefully.

**Comment by shumdeveloper** [comment]
> Hey, You can 🙃 though I had no issues with that, I'll take a closer look later this week hopefully.

Please, it's too important. Library just doesn't work correctly with this issue. I can't secure my queries or mutations. This is a primary issue. With this, I can't use this library

**Comment by nrbnlulu** [comment]
Hey, I tied to reproduce though it worked fine for me.. can you share an MRE?

**Comment by nrbnlulu** [comment]
@shumdeveloper Are you using GraphiQL to send the headers?

**Comment by shumdeveloper** [comment]
> @shumdeveloper Hey, I tried to reproduce though it worked fine for me.. can you share an MRE?

Before I got _"Expected Iterable, but did not find one for field"_ with 
TokenRequired, but now I tried it again and got a new error 
`TypeError: FruitQuery.__init__() missing 2 required keyword-only arguments: 'fruit' and 'fruits'`

Reproduced it there: https://github.com/shumdeveloper/tokenrequired_issue_rep

**Comment by shumdeveloper** [comment]
> @shumdeveloper Are you using GraphiQL to send the headers?

I use postman with JWT header (in this case TokenRequired works fine, it tells any errors with token)

**Comment by brentpicasso** [comment]
All, I think this might have been due to our use of Django 3.x - I am now on Django 4.x and it seemed to have gone away with the original code. Does this make sense?

**Comment by brentpicasso** [comment]
I figured it out. It's related to pyjwt .  This error happens with 1.7.1 ; upgrading it (e.g. 2.6.0 solves the issue.
