### ISSUE TITLE
Passwordless Auth (Magic Links) with django-sesame

### ISSUE THREAD

**Issue by ren-chon** [nrbnlulu/strawberry-django-auth#184]
Hi,
I wanna ask if is it possible to use [django-sesame](https://github.com/aaugustin/django-sesame) that offers "magic links" for authenticating users without a password, with this package and how?

**Comment by nrbnlulu** [comment]
Hi You can create your own directive  extending `BaseDirective` and get the user object take the seasme token from the headers maybe..

**Comment by ren-chon** [comment]
Hi, sorry for being extremely late...
in their documentation I found about the get_token() which generates an auth token and get_user() authenticates the token and it works.
