### ISSUE TITLE
Support Django 4.1.3

### ISSUE THREAD

**Issue by maximyurevich** [nrbnlulu/strawberry-django-auth#206]

**Comment by nrbnlulu** [comment]
https://github.com/nrbnlulu/strawberry-django-auth/blob/cdfa757ce687b178163ac8459b8b02af3a80180a/.github/workflows/tests.yml#L27

Tests are already running against 4.1.3 wym?

**Comment by maximyurevich** [comment]
> https://github.com/nrbnlulu/strawberry-django-auth/blob/cdfa757ce687b178163ac8459b8b02af3a80180a/.github/workflows/tests.yml#L27
> 
> Tests are already running against 4.1.3 wym?

https://imgur.com/9TYpCOU.png

**Comment by nrbnlulu** [comment]
Whoops
https://github.com/nrbnlulu/strawberry-django-auth/blob/66842305a9411976639a8be75c37ed1eb6315bea/pyproject.toml#L28

**Comment by maximyurevich** [comment]
> https://github.com/nrbnlulu/strawberry-django-auth/blob/66842305a9411976639a8be75c37ed1eb6315bea/pyproject.toml#L28
> 
> make sure you have the latest version of this package..

I have Django 4.1.3, but when i removed django and install this package, django downgraded to 4.0.8

**Comment by nrbnlulu** [comment]
Maybe some other deps won't allow this, I will create a new release.

**Comment by maximyurevich** [comment]
> Maybe some other deps won't allow this, I will create a new release.

When will it be available on pypi?

**Comment by nrbnlulu** [comment]
~10 minutes
