### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by muhammadfaruq72** [nrbnlulu/strawberry-django-auth#218]
Hey, Thank you for the amazing work.

I'm having this weird Issue while registering a user. Can you identify the issue? I'm using Postgres database.

And also, Do you have some more code examples so I can get to know it better? I really appreciate that.

![Screenshot 2022-12-08 at 4 59 05 AM](https://user-images.githubusercontent.com/51035641/206323591-5a8a82f5-c22b-44b3-a036-d216558f5f05.png)

**Comment by nrbnlulu** [comment]
Hey! do you have a stacktrace?

**Comment by muhammadfaruq72** [comment]
> Hey! do you have a stacktrace?

I was doing something wrong, reinstalled everything and it works. Thank you!
