### ISSUE TITLE
Support for Python 3.11?

### ISSUE THREAD

**Issue by briant-spindance** [nrbnlulu/strawberry-django-auth#228]
Does strawberry-django-auth support 3.11? I see it listed on the badge, but when I try to install it via poetry, I get this error:

The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
  - strawberry-django-auth requires Python >=3.8,<3.11, so it will not be satisfied for Python >=3.11,<4.0

**Comment by nrbnlulu** [comment]
oh it is just poetry thing, I'll need to update pyproject.toml.. other than that tests are running agianst 3.11 as well.
