### ISSUE TITLE
Configuration to support user model without username and first_name/last_name

### ISSUE THREAD

**Issue by 13hakta** [nrbnlulu/strawberry-django-auth#230]
# Prerequisites

* [ ] Is it a bug?
* [x] Is it a new feature?
* [x] Is it a question?
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/nrbnlulu/strawberry-django-auth/blob/master/CONTRIBUTING.md) guide.

# Description

Please provide an example for configuring to case when user has email as username (so there is no `username` field) and `name` field instead of two first_name/last_name.

## Expected behavior

Runs without errors with custom user model.

## Actual behavior

Library is adapted for common use case when user model has username and first_name/last_name fields.

**Comment by nrbnlulu** [comment]
https://github.com/nrbnlulu/strawberry-django-auth/blob/d4f4ed3b5568575f82a8e0668052cee4237ab717/testproject/settings_b.py#L22

**Comment by 13hakta** [comment]
> https://github.com/nrbnlulu/strawberry-django-auth/blob/d4f4ed3b5568575f82a8e0668052cee4237ab717/testproject/settings_b.py#L22
> 
> Is that what you are looking for?

It was close, but not enough...Main challenge was with correct types for set of fields.
Finally after few hours I made a working solution. I leave it here for history. Used python 3.10. Django 4+

in settings.py:
```
from dataclasses import field
from typing import Optional
from gqlauth.settings_type import GqlAuthSettings, email_field
from strawberry.annotation import StrawberryAnnotation
from strawberry.field import StrawberryField

...

# https://docs.djangoproject.com/en/dev/ref/settings/#auth-user-model
AUTH_USER_MODEL = "users.User"

name_field = StrawberryField(
    python_name="name",
    default=None,
    type_annotation=StrawberryAnnotation(Optional[str]),
)

GQL_AUTH = GqlAuthSettings(
    SEND_ACTIVATION_EMAIL=False,
    LOGIN_REQUIRE_CAPTCHA=False,
    REGISTER_REQUIRE_CAPTCHA=False,
    JWT_PAYLOAD_PK=field(default_factory=lambda: email_field),
    LOGIN_FIELDS=set([email_field]),
    REGISTER_MUTATION_FIELDS=set([email_field]),
    UPDATE_MUTATION_FIELDS=set([name_field]),
)
```

Define `UserManager` yourself. In user model:
```
class User(AbstractUser):
    name = CharField(_("Name of User"), blank=True, max_length=255)
    email = EmailField(_("EMail"), blank=False, unique=True)
#    first_name = None  # type: ignore
#    last_name = None  # type: ignore
#    username = None  # type: ignore

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()
```
