### ISSUE TITLE
Allow multiple authentication backend

### ISSUE THREAD

**Issue by LinnaViljami** [nrbnlulu/strawberry-django-auth#268]
# Description

If additional authentication backend provided gql auth 'gqlauth.core.middlewares.django_jwt_middleware' throws an error. d

```
File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 127, in login raise ValueError(
ValueError: You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user.
```

**Comment by nrbnlulu** [comment]
Curentlly it is not a backend but a middleware

**Comment by LinnaViljami** [comment]
Yes, I know. That is not the problem. But the problem is, that the middleware calls django building login() function without providing an optional "backend" argument. So when an additional way to login is provided (by defining another authentication backend) your middleware throws an error. 

This bug can be fixed just adding an extra parameter when calling login in the middleware `login(request, user, backend='django.contrib.auth.backends.ModelBackend')`

**Comment by LinnaViljami** [comment]
Okay, this bug is maybe related to a deeper misunderstanding of how Django authentication system should work. I try to explain my opinion and @nrbnlulu or the others can challenge it. I may have also misunderstood something for example related to refresh token

## Django authentication system & JWT tokens
- The basic Django authentication system uses basic authentication and sessions stored in the backend, JWT tokens instead do not require backend sessions to be stored, except refresh tokens.

## Django authentication flow & JWT tokens
1. Session middleware tries to fetch the session from the backend session store based on the session id stored in request user cookies. The session is then set to request context JWT token session is not held in the session store so the session is not found, and so it is not set to user context.
2. Authentication middleware tries to fetch the session user id and the authentication backend that is used to init the session. Then it tries to fetch the user by the user id calling the authentication backend get_user() method. The get user method should then return the user instance or AnonymousUser(). When dealing with JWT tokens, the session is not found and an anonymous user will be returned if no extra middleware is provided

## Django login function
- Django login function attach authenticated user into session. So it inits a new session for the given user. When using JWT tokens there is no need to call the login function (except maybe refresh tokens) because we do not use backend sessions.

## Current implementation
- Django login function is called every time in the `django_jwt_middleware` thus initializing a new session in every request. 
- The user last login field is not updated when obtaining JSONWebToken, instead, it is updated in every request if the user has a valid JWT cookie

## In my mind the proper way to implement this
- Django login function is never called when dealing with JWT tokens
- JWT token middleware should instead just decode the JWT token, fetch the user with a primary key if the token is valid and then set the user into request context, otherwise return AnonymousUser.

**Comment by nrbnlulu** [comment]
> When using JWT tokens there is no need to call the login function

It is required for users that might use other auth backends also, it sets last `logged_in` field and possibly other magic stuff...
I originally wanted to ad this as a backend though I had issues with async, I think it fits better there.

**Comment by LinnaViljami** [comment]
I tried the current solution, due to the login call in middleware, user is authenticated even if I remove the whole JWT token. So what actually happens now:
1. User has a valid JWT token, so django_jwt_middleware validates token, and call django built-in login function
2. Django logs user in and init new database session, and sets session cookie to the user (this is not meant to happen if we speak about JWT tokens, it is all about basic authentication)
3. User removes his JWT token and not set it anymore, still because the basic authentication works, user is authenticated due to the unnecessary cookie and database session.

So many incorrect operations happen:
- Session is initialized and saved into database (the whole point of JWT tokens is that we do not need to init db session, instead user gets a signed token)
- User gets a basic authentication cookie (we don't want this since we use JWT tokens to authenticate)
- login() function is called in every request (even if we would not use JWT tokens, we should not login user in middleware) instead we maybe would want authenticate user using django authenticate() function, this is done automatically by django session and authentication middleware.

**Comment by LinnaViljami** [comment]
I do not know what is the "magic stuff" we need to django login call do, so please explain the issues you had.

If we speak about last_logged_in, it is not meant to being updated every time user query or mutate something with JWT token, instead we want to update it only, when user obtain a new JWT token. Also last_logged_in should be able to update without calling login() function

**Comment by nrbnlulu** [comment]
I agree, thanks.

**Comment by nas-me** [comment]
Hi

@LinnaViljami is right, i played with your solution before, when authentry was used with union for mutation.

Now that it was drop, i understand the choice for django session for permission, same approach with graphene.

In my use case, 

1- writing a javascript frontend that consume a strawberry api data, 

2- authentication with credentials to obtain a jwt token, 

3- run the me or the public query with the token to obtain a csrftoken from django response headers.

4- parse cookie from headers to get the csrftoken

5- set the csrftoken in headers for mutation with permission.

Can you please tell me what is the best approach :

Drop session and Write codes for mutations with jwt like you did before ? Meaning that I will need another logic to identify the user.

Stick to django session for permission and parse cookie from headers ?

Thanks

**Comment by dastanko** [comment]
> I ran some tests with insomnia using the django_jwt_middleware which as login call, due to the login call in middleware, user is authenticated even if I remove the whole JWT token. So what actually happens now:
> 
> User has a valid JWT token, so django_jwt_middleware validates token, and call django built-in login function
> Django logs user in and init new database session, and sets session cookie to the user (this is not meant to happen if we speak about JWT tokens, it is all about basic authentication)
> User removes his JWT token and not sent it anymore, still because the basic authentication works, user is authenticated due to the unnecessary cookie and database session initialized during steps 1 and 2
> So many incorrect operations happen:
> 
> Session is initialized and saved into database (the whole point of JWT tokens is that we do not need to init db session, instead user gets a signed token which we can verify without additional data saved into database)
> User gets a basic authentication cookie (we don't want this since we use JWT tokens to authenticate)
> login() function is called in every request (even if we would not use JWT tokens, we should not login user in middleware) instead we maybe would want authenticate user using django authenticate() function, this is done automatically by django session and authentication middleware.
> 

@LinnaViljami I confirm the behaviour that you have described. Have just stumbled on it. Leaving this message just in case, having similar issues. Will check out your solution.

**Comment by mnogokotin** [comment]
Hi. How should I now authenticate user through jwt? I send Authorization header with jwt token but my user is not authenticated (user.is_authenticated)

**Comment by nrbnlulu** [comment]
@mnogokotin please open another issue and provide some details on your setup
