### ISSUE TITLE
Dependency definitions cause a non-functioning version combination

### ISSUE THREAD

**Issue by lekksi** [nrbnlulu/strawberry-django-auth#351]
# Description

Dependency definitions cause a non-functioning strawberry libraries version combination

Poetry resolves to:
`strawberry-graphql = 0.163.2`
`strawberry-graphql-django = 0.9.2`
`strawberry-django-auth = 0.374.0`
`strawberry-django-plus = 1.35.2` 

These versions of `strawberry-graphql` and `strawberry-django-plus` seem to be incompatible (an import got broken due to the [strawberry release 0.160.0](https://github.com/strawberry-graphql/strawberry/releases/tag/0.160.0). Release notes for `0.160.0` state that a deprecation warning should be shown but I'm getting an exception).

The issue is fixed in the newer `strawberry-django-plus` versions (tested with `2.0.6`) but the current `0.374.0` release of `strawberry-django-auth` requires `strawberry-django-plus = ">=1.25.2,<2.0.0"`.

# Proposed fix 

A release with the most recent changes in this repo would fix the issue. More specifically [this commit](https://github.com/nrbnlulu/strawberry-django-auth/commit/7bdbbe62eda6e4d8bde6dfcdd1a6faa8769fc38a).

I tested that everything works without a problem when installing this package directly from the `main` branch.

**Comment by lekksi** [comment]
Hey, thanks for the quick response @nrbnlulu ! Unfortunately it looks like the [release failed to auth error](https://github.com/nrbnlulu/strawberry-django-auth/actions/runs/4511873392/jobs/7944624684).

**Comment by nrbnlulu** [comment]
Oh thanks, didn't noticed..

**Comment by nrbnlulu** [comment]
should be fixed in [0.374.2](https://github.com/nrbnlulu/strawberry-django-auth/commit/498c9f0596793118d870f33d116b7debd67b0acd) can you confirm?

**Comment by lekksi** [comment]
@nrbnlulu yes, works with 0.374.2! Thanks!
