### ISSUE TITLE
Authenticated queries run without JWT token

### ISSUE THREAD

**Issue by eddienko** [nrbnlulu/strawberry-django-auth#356]
# Prerequisites

* [x] Is it a bug?
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?

# Description

Authorized queries are executed without JWT token in the header. I am using the latest release version 0.374.1. 

# Steps to Reproduce

Follow the tutorial right up to the end, the `me` query is executed:

1. Run the `me` query without JWT token. The query fails -> good
2. Run the `me` query with JWT token in the header. The query is executed and returns correct values -> good
3. Run the `me` query without JWT token in the header, or with a wrong token . The query is again executed and returns the previous values -> **bug**

## Expected behavior

Authenticated queries should not be executed without correct JWT token.

## Actual behavior

Once the token is used once, it seems that consecutive queries succeed even if the token is not in the headers.

**Comment by eddienko** [comment]
I **guess** the problem is because using middlewares the user is already logged in using the Session and Authentication middlewares.

It looks like the following modification seems to work in this case, but not sure if it is the correct:

```
--- utils.py.bak	2023-03-25 19:37:17
+++ utils.py	2023-03-25 19:38:23
@@ -53,7 +53,7 @@


 def get_user(info: Info) -> USER_UNION:
-    return info.context.request.user  # type: ignore
+    return info.context.request.UserOrError.user  # type: ignore


 def cast_to_status_user(user: USER_UNION) -> UserProto:
```

**Comment by nrbnlulu** [comment]
I am not sure how to reproduce this or what is your solution, can you explain further?

**Comment by eddienko** [comment]
Sure:

```
git clone https://github.com/nrbnlulu/strawberry-django-auth.git
cd strawberry-django-auth/quickstart
python manage.py migrate
python -m  manage loaddata users.json. # THIS DOES NOT WORK
python manage.py createsuperuser. # admin / password
python manage.py runserver
```

Go to the iGraphQL interface @ http://127.0.0.1:8000 and do a signing:

```
mutation SignIn {
  tokenAuth(password: "password", username: "admin") {
    token {
      token
    }
  }
}
```

Then run the query:

```
query Me {
  me {
    username
  }
}
```

adding `{"Authorizarion": "JWT <your-token-here>"}`

After this do again the same query:

```
query Me {
  me {
    username
  }
}
```

removing the `Authorisation` header. This returns `username` instead of raising unauthenticated.

<img width="780" alt="Screenshot 2023-03-26 at 09 06 12" src="https://user-images.githubusercontent.com/3780274/227763382-b7d8bd49-de8d-419f-bb8c-8bc7ff12d327.png">
<img width="781" alt="Screenshot 2023-03-26 at 09 05 59" src="https://user-images.githubusercontent.com/3780274/227763371-7b992816-6047-45d3-abb7-b8cc450e47e8.png">

**Comment by nrbnlulu** [comment]
> python -m  manage loaddata users.json. # THIS DOES NOT WORK

This is a separate issue ig?

> removing the Authorization  header. This returns username instead of raising unauthenticated.

I don't think this is considered a bug, since we are authenticating against other django backends the user 
probably found in the django sessions backend. Don't you think?

**Comment by eddienko** [comment]
Yes, the fixtures is another issue, it is not important for me.

I think this is a bug because 1) it did not happen before the big refactoring (i.e. before you added the middleware) and 2) it allows me to perform queries when I use wrong JWT tokens (after I authenticate one time) which seems a security issue to me. I would expect that a query with a wrong token would return unauthorised.

**Comment by nrbnlulu** [comment]
IMO it's arguably a requirement you can bypass this implementing your own Token getter and you can raise exception there, I can't think of a nicer solution ATM. sorry :disappointed: 
https://github.com/nrbnlulu/strawberry-django-auth/blob/498c9f0596793118d870f33d116b7debd67b0acd/gqlauth/settings_type.py#L31

**Comment by keysmusician** [comment]
I ran into this as well, and indeed, it appears to be the result of Django's sessions. You pretty much have to decide if you want to use session authentication (with Django's built-in session management), token authentication (with this repo), or if you want to combine them for different purposes and manage the quirks which follow from that with your own code.

If you want to use JWT exclusively, you'll have to disable the Django session middleware.

I didn't realize until after I had set up JWT that just because you're authenticating through GraphQL doesn't mean you have to use JWT, you can still use sessions. You'll probably just have to write your own resolvers for it though because I'm not aware of a package which has session auth through Strawberry GraphQL preconfigured.

**Comment by johnklawlor** [comment]
What is confusing about this is that you can retrieve refresh and access tokens for a user, but there is no mechanism to authenticate with the tokens. Perhaps I am missing something.
1. What authentication backend are we supposed to use in order to authenticate a request that includes the access token?
2. Not strictly necessary, but certainly nice to have, is there a `@login_required` decorator in order to check if there exists an authenticated user in `info.context.request.user`?

**Comment by johnklawlor** [comment]
> 1. It depends if you use django or channels
I am using Django. What authentication backend should I use?

**Comment by nrbnlulu** [comment]
Probably the django backend :wink: 
https://nrbnlulu.github.io/strawberry-django-auth/tutorial/#install-strawberry-django-auth

**Comment by nrbnlulu** [comment]
going to close this since it isn't proved to be an issue rather a specific usecase for which I don't intend to support.

**Comment by johnklawlor** [comment]
> I ran into this as well, and indeed, it appears to be the result of Django's sessions. You pretty much have to decide if you want to use session authentication (with Django's built-in session management), token authentication (with this repo), or if you want to combine them for different purposes and manage the quirks which follow from doing so with your own code.
> 
> If you want to use JWT exclusively, you'll have to disable the Django session middleware.
> 
> I didn't realize until after I had set up JWT that just because you're authenticating through GraphQL doesn't mean you have to use JWT, you can still use sessions. You'll probably just have to write your own resolvers for it though because I'm not aware of a package which has session auth through Strawberry GraphQL preconfigured.

How do I disable session authentication in Django?

**Comment by keysmusician** [comment]
> > I ran into this as well, and indeed, it appears to be the result of Django's sessions. You pretty much have to decide if you want to use session authentication (with Django's built-in session management), token authentication (with this repo), or if you want to combine them for different purposes and manage the quirks which follow from doing so with your own code.
> > If you want to use JWT exclusively, you'll have to disable the Django session middleware.
> > I didn't realize until after I had set up JWT that just because you're authenticating through GraphQL doesn't mean you have to use JWT, you can still use sessions. You'll probably just have to write your own resolvers for it though because I'm not aware of a package which has session auth through Strawberry GraphQL preconfigured.
> 
> How do I disable session authentication in Django?

Check the Django docs, but there should be (at least one) middleware for it. You might be able to just remove the middleware. But keep in mind that may break other aspects of Django which expect session authentication to be available.
