### ISSUE TITLE
Set from_email as string instead of DjangoSetting object

### ISSUE THREAD

**Issue by kurttsam** [nrbnlulu/strawberry-django-auth#387]
## Problem

gqlauth/models.py --> class UserStatus --> def send(...):

```
    ... previous code ...

    return send_mail(
            subject=_subject,
            from_email=app_settings.EMAIL_FROM,
            message=message,
            html_message=html_message,
            recipient_list=(recipient_list or [getattr(self.user, USER_MODEL.EMAIL_FIELD)]),
            fail_silently=False,
        )
```

The `send_mail` method sets `from_email` to be an object of class `DjangoSetting` (This is set in another file where the `app_settings.EMAIL_FROM` is pointing to)
This causes a problem with 3rd party email backend which expects to get the `from_email` as a string.

## Solution proposal

modify the line `from_email=app_settings.EMAIL_FROM` to `from_email=app_settings.EMAIL_FROM.value`

The above solution fixes the issue at least in my case. Is there any reason why we should not use this solution?

**Comment by nrbnlulu** [comment]
> Is there any reason why we should not use this solution?

Yes, users wouldn't know that `GqlAuthDjangoSettings` is expecting a `DjangoSetting` also you are not allowed to access the settings object until all apps are ready.
This abstraction is required in order to retrieve other django settings after the django settings object has been defined. If you have another solution I would love to hear.

**Comment by nrbnlulu** [comment]
BTW I can't understand how does a 3rd app gets our  `DjangoSetting` object?

**Comment by kurttsam** [comment]
I am using anymail as an email backend in my Django project. When I try to send password reset email with gqlauth, the `send_email` (gqlauth/models.py line 50) gets called with attribute `from_email=app_settings.EMAIL_FROM` which is the same as `GqlAuthSettings.EMAIL_FROM=DjangoSetting("DEFAULT_FROM_EMAIL")`. This is where the `DjangoSetting` object is sent outside of gqlauth's scope.

This `send_email` function call is then passed through django/core/mail to anymail's email handler. The anymail's email handler tries to handle the `from_email` field, but it cannot read the value because it did not expect to get a `DjangoSetting` object in the `from_email` field.

**Comment by kurttsam** [comment]
I can see two possible solutions for this case:

1. Change the gqlauth/models.py line 52, where the values for an email message are sent for an email handler (email backend):
```
from_email=app_settings.EMAIL_FROM, #OLD
from_email=app_settings.EMAIL_FROM.value #NEW
```

2. (not optimal solution IMO) Add a __str__ method for `DjangoSetting` class:
```
    def __str__(self) -> str:
        return str(self.value)
```
and also make some changes for anymail package so that it accepts also an objects in case where the object has a __str__ method. I would not like to need to change two packages for just one simple use case :D


So, the solution 1 is not going to change the GqlDjangoSettings at all. The GqlDjangoSettings would still have the DjangoSetting object in use.

**Comment by nrbnlulu** [comment]
@kurttsam Can you checkout into #391 and see if it is fixed?

**Comment by kurttsam** [comment]
Thanks, works fine!

**Comment by nrbnlulu** [comment]
feel free to close this if it is fixed.
