### ISSUE TITLE
Register mutation requires users UUID input to register

### ISSUE THREAD

**Issue by henryfool91** [nrbnlulu/strawberry-django-auth#4]
# Prerequisites

* [x] Is it a a question?
* [X] Are you running the latest version?

# Description
Hello! Thanks for a adaption of a good package to strawberry!
But i can`t get it work (i think original docs are little bit outdated and controversial), could you give me direction or a example of using register mutation + email verification?
I tried to import arg_mutations ("from from gqlauth.user import arg_mutations"), and use it like
```
from gqlauth.user import arg_mutations as mutations

@strawberry.type
class AuthMutations:
    register = mutations.Register.Field

#settings.py
GQL_AUTH = {
    'LOGIN_ALLOWED_FIELDS': ['email'],
    "LOGIN_REQUIRED_FIELDS": ["email", "password"],
    'REGISTER_MUTATION_FIELDS': ['email'],
    'USERNAME_FIELD': ['email'],
}
```

But this register mutation requires users UUID input to register:)
![Screenshot 2022-04-25 at 13-44-00 Strawberry GraphiQL](https://user-images.githubusercontent.com/82047953/165074429-8128de75-e9e9-40fc-98f3-47105cbcd697.png)

Am i doing somethig wrong?
I have a CustomUser model, django 4.0.4

Thanks in advance!

**Comment by nrbnlulu** [comment]
Hey, the docs are indeed outdated (i only changed some `.md` files but nothing serious).
it seems that you are running a previous version where the resolvers was getting the user from a uuid field (i was messing around with relay with not much success)
as per version [2.3 ](https://pypi.org/project/strawberry-django-auth/0.2.3/) this is fixed.
are you sure you are running the latest version?

**Comment by nrbnlulu** [comment]
please
