### ISSUE TITLE
Remove strawberry_django_plus dependency

### ISSUE THREAD

**Issue by iacobfred** [nrbnlulu/strawberry-django-auth#402]
https://github.com/blb-ventures/strawberry-django-plus

This library has been merged into the core strawberry-django (https://github.com/strawberry-graphql/strawberry-graphql-django) library so can be removed as a dependency of strawberry-django-auth.

There's a migration guide: https://blb-ventures.github.io/strawberry-django-plus/migration-guide/#migrating-to-strawberry-django

**Comment by brentpicasso** [comment]
+1 on this request.  Thanks!

**Comment by nrbnlulu** [comment]
it will be removed once #398 is resolved.
