### ISSUE TITLE
TokenAuth returning "invalid_credentials"

### ISSUE THREAD

**Issue by owen-dyer** [nrbnlulu/strawberry-django-auth#415]
I'm using a custom user model (which inherits from AbstractBaseUser). I have a custom authentication backend setup which allows login via email and username. I can register users and verify them, however, when I try to login via the token_auth method I get the following response:

{
  "data": {
    "tokenAuth": {
      "success": false,
      "errors": {
        "nonFieldErrors": [
          {
            "message": "Please, enter valid credentials.",
            "code": "invalid_credentials"
          }
        ]
      },
      "token": null,
      "user": null
    }
  }
}

I'm not sure what is going wrong as it returns 200 lol. Any help is much appreciated. I can provide more information from my side as requested.

**Comment by nrbnlulu** [comment]
> I can provide more information from my side as requested.

Yeah :upside_down_face: that would be nice.

**Comment by owen-dyer** [comment]
> Yeah 🙃 that would be nice.

Haha I figured it out, stupid error on my end. I figured that I might as well just debug it by myself.
For others that have this error in the future:
For me it was because in my custom user model I have 'is_active' set to false by default and assumed that verifying my user via the function from this library would change that, but it didn't.

**Comment by phaniophrero** [comment]
Hi this is what happened to me too, so what did you do with the `is_active` field? removed it?

**Comment by owen-dyer** [comment]
> Hi, this is what happened to me too, so what did you do with the `is_active` field? So I've just set the `is_active` field to `true` as default `is_active = models.BooleanField(default=True)` and it works, is that the right fix?

That is one fix, but not the best one if you want it to be false by default. You need to add some code so that when you verify the account the 'is_active' field for the current user is switched to True. To do this you can use the 'filter' method from your model and use the identifier from the token as the input.

**Comment by phaniophrero** [comment]
Do you have an example of that?

**Comment by owen-dyer** [comment]
> Do you have an example of that?

Edit the 'verify' method in '...gqlauth/models.py' module. It is in the 'UserStatus' class. You only need to add 2 lines of code and I think it is important for people to learn, so I think that you should try to do this yourself. If you cannot figure it out after trying to a bit then please come back here and we can help. The required lines are very similar to the code in the same function. I hope that this solves your issue.

**Comment by phaniophrero** [comment]
I don't have a UserStatus class ...
this is my custom user model :

```
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import  BaseUserManager
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, first_name, last_name, password=None):
        """ Create and save a User with the given email and password """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, password, first_name, last_name):
        """ Create and save a SuperUser with the given email and password. """

        user = self._create_user(
            email=self.normalize_email(email),
            password=password,
            first_name=first_name,
            last_name=last_name,
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save(using=self._db)
        return user
    

    def verifyAccount(self, user, user_input, code):
        if user_input == code:
            user.is_active = True
            user.save(using=self._db)
            return user


class CustomUser(AbstractBaseUser):
    id = models.AutoField(primary_key=True, editable=False)
    email = models.EmailField(blank=False, max_length=255, unique=True, verbose_name="email address")
    first_name = models.CharField(max_length=255, verbose_name="first_name")
    last_name = models.CharField(max_length=255, verbose_name="last_name")
    profile_image = models.ImageField(null=True, blank=True) 
    # profile_image = models.ImageField(default="../media/default_avatar.png", null=True, blank=True) 
    date_of_birth = models.DateField(blank=False, null=True, verbose_name="date_of_birth")
    phone = models.CharField(blank=False, max_length=12, verbose_name="phone")
    country = models.CharField(blank=False, max_length=150, verbose_name="country")
    city = models.CharField(blank=True, max_length=150, verbose_name="city")
    zip_code = models.CharField(blank=True, max_length=5, verbose_name="zip_code")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    # is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True
```
So I've tried using the same function from the UserManager, the verifyAccount one, but is not working, I need to get the token from graphql_auth and change the status of is_active from false to true, but how can I do that, or where is the place to do that in the same user model file ?

**Comment by owen-dyer** [comment]
> I don't have a UserStatus class

The 'UserStatus' class is part of the 'strawberry-django-auth' library. I'm not sure when it was added but I think that you should have it. You need to add the functionality of changing 'is_active' from false to true when the user is verified within the method from 'strawberry-django-auth'.

**Comment by phaniophrero** [comment]
Look I appreciate the quick response, but still where I should have this UserStatus class inside my user model file 
? or a different file? could you please share an example of that ?

**Comment by phaniophrero** [comment]
And I also noticed that some fields are not available when logging in the user using `tokenAuth` mutation,
for example I have date_of_birth and profile_image fields and is_admin filed is not showing as well
