### ISSUE TITLE
unexpected keyword argument 'LOGIN_ALLOWED_FIELDS' on example settings

### ISSUE THREAD

**Issue by henryfool91** [nrbnlulu/strawberry-django-auth#42]
Hi! I`m getting error "unexpected keyword argument 'LOGIN_ALLOWED_FIELDS'" when use example code from docs:
```
# settings.py
from gqlauth.settings_type import GqlAuthSettings

GQL_AUTH = GqlAuthSettings(
    LOGIN_ALLOWED_FIELDS = ['email', 'username'],
)
```
May be that setting was renamed to "LOGIN_REQUIRED_FIELDS" ?

Also, i am getting "CustomUser has no field named 'username'," with default settings, can you give me direction what should i change if my CustomUser model don`t have 'username' field?

Thanks in advance!

**Comment by nrbnlulu** [comment]
Indeed. don't you get type hints from your IDE?

**Comment by nrbnlulu** [comment]
> Also, i am getting "CustomUser has no field named 'username'

Maybe it is a bug.. I need to check that.

**Comment by nrbnlulu** [comment]
It is a bug [here](https://github.com/nrbnlulu/strawberry-django-auth/blob/2273f870647ae1c7f399c721e1b6a6280d616765/gqlauth/user/resolvers.py#L446)

**Comment by nrbnlulu** [comment]
@AriaMoradi @henryfool91 Please make sure that the new release resolves this one.

**Comment by henryfool91** [comment]
It is working now, thanks a lot!

**Comment by lifeeric** [comment]
hi, it's not not working for me, the error I get:

```shell
TypeError: GqlAuthSettings.__init__() got an unexpected keyword argument 'LOGIN_ALLOWED_FIELDS'
```

model.py
```py
# users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

    email = models.EmailField(blank=False, max_length=254, verbose_name="email address", unique=True)
    USERNAME_FIELD = "email"   # e.g: "username", "email"
    # EMAIL_FIELD = "email"         # e.g: "email", "primary_email"

    REQUIRED_FIELDS = []
```

and also I want only email for register mutation, but I need to provide both email && username. how can I overcome both issues?

thank you so much ❤️

**Comment by nrbnlulu** [comment]
Hey, @lifeeric since version 3.4.1 there is no `LOGIN_ALLOWED_FIELDS` instead ther is `LOGIN_FIELDS` and you will need to provide a set of strawberry fields so you can make the strawberry field optional if you would like.
