### ISSUE TITLE
support for LOGIN_ALLOWED_FIELDS

### ISSUE THREAD

**Issue by AriaMoradi** [nrbnlulu/strawberry-django-auth#45]
I'm porting my graphene-django project to strawberry and it used `graphene-django-auth` for handling jwt auth.

# Description
Support for `LOGIN_ALLOWED_FIELDS` is mentioned in settings docs but no place in the code does respect it.
My app uses a custom user and users can authenticate with `phone_number` and `password` or `username` and `password`.

# Steps to Reproduce

1. Try porting settings from `graphene-django-auth` 
```
GRAPHQL_AUTH = {
    'LOGIN_ALLOWED_FIELDS': ['phone_number', 'username'],
}
```
2. `GqlAuthSettings` should support this field as per docs
3. The field doesn't exist 

## Expected behavior
Support should be provided if this package aims to cover features provided by `graphene-django-auth` 

## Actual behavior
Doesn't work.

# Requirements
```
aiohttp==3.8.1
aiosignal==1.2.0
asgiref==3.5.2
async-timeout==4.0.2
attrs==21.4.0
backports.cached-property==1.0.2
cached-property==1.5.2
certifi==2022.6.15
charset-normalizer==2.1.0
click==8.1.3
Django==4.0.6
django-admin-display==1.3.0
django-ckeditor==6.4.2
django-cors-headers==3.13.0
django-debug-toolbar==3.5.0
django-filter==22.1
django-js-asset==2.0.0
django-multiselectfield==0.1.12
django-taggit==3.0.0
djangorestframework==3.13.1
frozenlist==1.3.0
graphql-core==3.2.1
idna==3.3
isodate==0.6.1
jdatetime==4.1.0
lxml==4.9.1
multidict==6.0.2
packaging==21.3
Pillow==9.2.0
platformdirs==2.5.2
Pygments==2.12.0
PyJWT==2.4.0
pymemcache==3.5.2
pyparsing==3.0.9
python-dateutil==2.8.2
python-multipart==0.0.5
pytz==2022.1
requests==2.28.1
requests-file==1.5.1
requests-toolbelt==0.9.1
six==1.16.0
sqlparse==0.4.2
strawberry-django-auth==0.3.3.1
strawberry-django-jwt==0.2.1
strawberry-django-plus==1.20.2
strawberry-graphql==0.119.1
strawberry-graphql-django==0.4.0
typing_extensions==4.3.0
urllib3==1.26.10
yarl==1.7.2
zeep==4.1.0
```

**Comment by AriaMoradi** [comment]
looks like a duplicate of #42?

**Comment by nrbnlulu** [comment]
hopefully I will work on it tonight.  
What is you `USERNAME_FIELD` in the django model?

**Comment by AriaMoradi** [comment]
Its `username`.
Consider that it's totally possible to have a custom `UserManager` and ignore `USERNAME_FIELD` altogether.

**Comment by nrbnlulu** [comment]
I am wondering if we would use the fields provided in LOGIN_REQUIRED_FIELDS to query the django user will suffice?

**Comment by AriaMoradi** [comment]
ref: https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD

According to that, you'll need a custom auth backedend to support that

**Comment by nrbnlulu** [comment]
Are you O.K with me using the user setup you posted here for tests?

**Comment by AriaMoradi** [comment]
That piece of code is based on https://github.com/wejhink/django-phone-login which is licensed under BSD, you can use my modified code with any license you like.
