### ISSUE TITLE
Authenticating user with other authentication backends

### ISSUE THREAD

**Issue by AriaMoradi** [nrbnlulu/strawberry-django-auth#46]
I'm wondering how I could make use of django's authentication capabilities? This package and jwt seem to provide a non-standard (at least in it's own system) method to authenticate user (`JSONWebTokenMiddleware`)?

An example use case might be that I may want to first log in with django admin and then use session authentication for resolving user in `me` query, later the react front end will use JWT auth.

This is possible in django rest framework.
ref: https://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme

Update:
- I could access the authenticated user by `info.context.request.user`. 
- `gqlauth.user.queries.UserQueries` uses `g_user` which in turn is accessing `info.context.user`, this seems to be filled in by `JSONWebTokenMiddleware` which doesn't seem to work as intended?!

**Comment by nrbnlulu** [comment]
I think django will call all the authentication backends you have, one of them being `JSONWebTokenMiddleware` this middleware will search for Authentication header or a cookie (I didn't used cookie yet).  
as for `g_user` sometimes the user would be in  `info.context` and sometimes in `info.context.request` so this is just an helper for that..

**Comment by AriaMoradi** [comment]
> I think django will call all the authentication backends you have, one of them being JSONWebTokenMiddleware this middleware will search for Authentication header or a cookie (I didn't used cookie yet).
That doesn't makes sense, we add `GraphQLAuthBackend` or `JSONWebTokenBackend` to `AUTHENTICATION_BACKENDS` which will return the authenticated user or AnonymousUser.

`JSONWebTokenMiddleware` is an Schema extension.

I'm confused.

> as for g_user sometimes the user would be in info.context and sometimes in info.context.request so this is just an helper for that.

what's that "sometimes" here? why isn't `info.context.user` always set? Is this an implementation difference between graphene and strawberry?

**Comment by nrbnlulu** [comment]
sorry you are correct In graphene it was in django middlewares, now the author of jwt did that in schema extension.
And about the user the creator of this library used to inject the user in tests to a `RequestFactory` (maybe in graphene and in graphene I think the user was in request obj).  
 recently I changed that and I the tests runs against `django.tests.Client/AsyncClient` so I don't inject the user there and also not inside context.  
 I will see if that `g_user` is really redundant. 

>I'm wondering how I could make use of django's authentication capabilities? This package and jwt seem to provide a non-standard (at least in it's own system) method to authenticate user (JSONWebTokenMiddleware)?

>An example use case might be that I may want to first log in with django admin and then use session authentication for resolving user in me query, later the react front end will use JWT auth.

I am not familiar with django "standard" way of authenticating but if you have any ideas I would love to help on that.    

Also I am not anywhere near a pro django'er or something so don't expect me to know everything...   
I am just a guy that was using this library in graphene and when I realized that graphene is dead I needed to migrate to strawberry and I learned on the way so to speak.  I did put a lot of effort in this project though and I think that overall it is going in the right direction.

**Comment by AriaMoradi** [comment]
Having some piece of code/middleware somewhere that injects `info.context.user` and mentioning it in docs will go a long way. Strawberry django docs on this are very ambiguous (at least for me coming from django rest framework). Maybe even a pull request to that package could solve it all. 

> Also I am not anywhere near a pro django'er or something so don't expect me to know everything...
I am just a guy that was using this library in graphene and when I realized that graphene is dead I needed to migrate to strawberry and I learned on the way so to speak. I did put a lot of effort in this project though and I think that overall it is going in the right direction.

That's the way everyone does it. Even more so the creators of libraries/frameworks/standards/etc.

**Comment by nrbnlulu** [comment]
Re 1: Sorry I didn't understood how strawberry django is related here?

Generally I think that Strawberry and Django are built very differently.  
Strawberry is all about typing while in django (probably beacause of its age) there are so many
 raw strings and dicts flying around..

**Comment by nrbnlulu** [comment]
A quick look at 
https://github.com/KundaPanda/strawberry-django-jwt/blob/17d520efcb1f2e2cfefc2744d283b7c93ea8d540/strawberry_django_jwt/auth.py#L30  

seems like all the authentication backends already being called. So what do you mean exactly?

**Comment by AriaMoradi** [comment]
Here's the code I came up after digging through the library
Uses the helper from https://github.com/KundaPanda/strawberry-django-jwt/issues/338
```python
@gql.mutation
    def token_auth(self, info: Info, password: str, username: Optional[str] = None,
                   phone_number: Optional[str] = None) -> TokenDataType:
        """
        obtain JWT token
        compatible with `strawberry_django_jwt.mutations.ObtainJSONWebToken.obtain`
        """
        if username is not None:
            user = authenticate(username=username, password=password)
        elif phone_number is not None:
            phone_number = PhoneNumberField().to_internal_value(phone_number)
            user = authenticate(phone_number=phone_number, password=password)
        else:
            raise Exception("This mutation needs at least one of username or phone number to authenticate user.")
        if user is not None:
            return generate_jwt_token_payload(info, user)
        raise Exception("Please enter valid credentials")
```

**Comment by nrbnlulu** [comment]
Ref https://github.com/KundaPanda/strawberry-django-jwt/issues/134

**Comment by nrbnlulu** [comment]
We call `authenticate` here https://github.com/nrbnlulu/strawberry-django-auth/blob/aca6eb22a1a7c7b569d3c79763b58ae89918e776/gqlauth/jwt/types_.py#L172

This calls all django authentication backends with the fields you defined for login mutation.
Ref: https://docs.djangoproject.com/en/4.1/topics/auth/default/#authenticating-users
