### ISSUE TITLE
New patches for Django 5.0

### ISSUE THREAD

**Issue by SirBigG** [nrbnlulu/strawberry-django-auth#466]
Hello, people! There is a problem with updating the new patch version of Django (5.0.1) because of this strict <=5.0 check. Let's make at least <5.1 . Thank you.

**Comment by kfields** [comment]
Yeah, it's a shame.  I suggest <6.0

**Comment by nrbnlulu** [comment]
PR is welcomed

**Comment by kfields** [comment]
I'm working on a PR.  I have the next three days off so keep your fingers crossed.
It's more involved than just bumping the Django version.  I'll go into more detail when I submit it.

**Comment by evanheckert** [comment]
Need any help with this? @kfields

**Comment by kfields** [comment]
I've got it under control.  Just needs some final touches.  I'm pretty sure I can submit it over the weekend.
Thanks @evanheckert

**Comment by nrbnlulu** [comment]
should be fixed in #504 please reopen this otherwise.
