### ISSUE TITLE
Do you need maintenance help?

### ISSUE THREAD

**Issue by thclark** [nrbnlulu/strawberry-django-auth#468]
# Description

@nrbnlulu I see this library as an important part of strawberry-django (and in future an important part of any django app; since once you go graph you don't go back!).

But AFAICT it's just you maintaining an ever-increasing issue list, and there's a stack of PRs dating back almost a year.

Are you in need of help/sponsorship with this project?

If so perhaps we can jump on a call and talk about whether there's a way to help you out.

**Comment by nrbnlulu** [comment]
The current state of the project is that I passivelly maintain it. Meaning I'll accept PR's though I am not working on featutes or bug fixes unless I need in my app.

**Comment by janbaykara** [comment]
Hey @thclark, appreciate you offering to support this repo. I just wanted to check if you were still willing to push this forwards with @nrbnlulu?

**Comment by nrbnlulu** [comment]
>  push this forwards with @nrbnlulu?
wym?

**Comment by thclark** [comment]
> Hey @thclark, appreciate you offering to support this repo. I just wanted to check if you were still willing to push this forwards with @nrbnlulu?

I had hoped to be added as a maintainer properly but the messages above suggested that wasn't wanted.

I don't spend hours/days making PRs for libraries unless I **know** I can get them merged - it's fine if there's an active project, lots of maintainers and a roadmap so you can check what you're doing is inline with the plan. But for smaller libraries like this I find that work gets wasted - PRs drag on forever or never get merged. So to contribute properly you need to have the agency to resolve existing PRs, come up with a roadmap, triage enquiries and generally drive things forward.

That's what I mean by maintenance help. But to be honest since my original offer i've been erring toward doing my own thing anyhow, sorry!
