### ISSUE TITLE
Could not get quickstart project to work

### ISSUE THREAD

**Issue by NeutrinoDot** [nrbnlulu/strawberry-django-auth#490]
# Description

I tried running through the Quickstart Tutorial. I got to the MeQuery but failed to authenticate the user. I traced the function calls and it looks like info.context.request.user was set to Anonymous user.

# Steps to Reproduce

1. Run through the entire Tutorial. I was careful to update the token before expiration.

## Expected behavior

Expected successful authentication from the me query.

## Actual behavior

Received "message": "Unauthenticated." in the query response.

# Requirements

WSL2
Python 3.10.12
asgiref==3.7.2
Django==4.2.11
django-stubs==4.2.7
django-stubs-ext==4.2.7
graphql-core==3.2.3
mypy==1.7.1
mypy-extensions==1.0.0
PyJWT==2.8.0
python-dateutil==2.9.0.post0
six==1.16.0
sqlparse==0.4.4
strawberry-django-auth==0.376.5
strawberry-graphql==0.220.0
strawberry-graphql-django==0.35.1
tomli==2.0.1
types-pytz==2024.1.0.20240203
types-PyYAML==6.0.12.20240311
typing_extensions==4.10.0

**Comment by nrbnlulu** [comment]
Hi, the docs should be updated please take a look at #483

**Comment by NeutrinoDot** [comment]
thank you. That worked for me.
