### ISSUE TITLE
TokenType.is_expired() fails since it's comparing naive timestamp with aware timestamp

### ISSUE THREAD

**Issue by shmoon-kr** [nrbnlulu/strawberry-django-auth#574]
# Prerequisites

* [V] Is it a bug?

# Description

I found that the library raises an error when validating a token.
I looked at details and found the the error was raising from the following function.

```
class TokenType:
    payload: TokenPayloadType
    token: str = strawberry.field(description="The encoded payload, namely a token.")

    def is_expired(self):
        return self.payload.exp < utc_now()
```

In self.payload.exp < utc_now() statement, it's comparing naive timestamp from decoded JWT and aware timestamp from utc_now() function. It was the root cause of the error.
So, I tried to change it with self.payload.exp.replace(tzinfo=timezone.utc) and the error was disappeared.

I'll make a PR.

# Steps to Reproduce

Any queries with JWT fails.

**Comment by nrbnlulu** [comment]
What version are you running?
Also make sure you don't override this in an incompatible manner
https://github.com/nrbnlulu/strawberry-django-auth/blob/main/gqlauth/settings_type.py#L240

**Comment by shmoon-kr** [comment]
This is a part of my requirements.txt file.

```
strawberry-graphql[channels,debug-server]==0.237.1
strawberry-graphql-django==0.47.1
strawberry-django-auth==0.377.0
```

and this is a part of my settings.py

```
GQL_AUTH = GqlAuthSettings(
    ALLOW_LOGIN_NOT_VERIFIED=True,
    LOGIN_FIELDS={username_field, password_field},
    LOGIN_REQUIRE_CAPTCHA=False,
    REGISTER_MUTATION_FIELDS={username_field},
    REGISTER_REQUIRE_CAPTCHA=False,
    CAPTCHA_EXPIRATION_DELTA=timedelta(seconds=120),
    CAPTCHA_MAX_RETRIES=5,
    # CAPTCHA_TEXT_FACTORY=default_text_factory,
    # CAPTCHA_TEXT_VALIDATOR=default_captcha_text_validator,
    FORCE_SHOW_CAPTCHA=False,
    CAPTCHA_SAVE_IMAGE=False,
    UPDATE_MUTATION_FIELDS={},

    # email tokens
    EXPIRATION_ACTIVATION_TOKEN=timedelta(days=7),
    EXPIRATION_PASSWORD_RESET_TOKEN=timedelta(hours=1),
    EXPIRATION_PASSWORD_SET_TOKEN=timedelta(hours=1),

    # email stuff
    #EMAIL_FROM: DjangoSetting[str] = DjangoSetting("DEFAULT_FROM_EMAIL")
    SEND_ACTIVATION_EMAIL=True,
    ACTIVATION_PATH_ON_EMAIL="activate",
    PASSWORD_SET_PATH_ON_EMAIL="password-set",
    PASSWORD_RESET_PATH_ON_EMAIL="password-reset",

    # email subjects templates
    EMAIL_SUBJECT_ACTIVATION="email/activation_subject.txt",
    EMAIL_SUBJECT_ACTIVATION_RESEND="email/activation_subject.txt",
    EMAIL_SUBJECT_PASSWORD_SET="email/password_set_subject.txt",
    EMAIL_SUBJECT_PASSWORD_RESET="email/password_reset_subject.txt",

    # email templates
    EMAIL_TEMPLATE_ACTIVATION="email/activation_email.html",
    EMAIL_TEMPLATE_ACTIVATION_RESEND="email/activation_email.html",
    EMAIL_TEMPLATE_PASSWORD_SET="email/password_set_email.html",
    EMAIL_TEMPLATE_PASSWORD_RESET="email/password_reset_email.html",
    #EMAIL_TEMPLATE_VARIABLES=field(default_factory=lambda: {}),

    # others
    ALLOW_DELETE_ACCOUNT=False,
    ALLOW_PASSWORDLESS_REGISTRATION=False,
    SEND_PASSWORD_SET_EMAIL=False,

    # JWT stuff
    #  JWT_SECRET_KEY=DjangoSetting("SECRET_KEY")
    JWT_ALGORITHM="HS256",
    JWT_TIME_FORMAT="%Y-%m-%dT%H:%M:%S.%f",
    #  JWT_PAYLOAD_HANDLER: Callable[["UserProto"], "TokenType"] = create_token_type
    JWT_PAYLOAD_PK=id_field,
    #  JWT_DECODE_HANDLER: Callable[[str], "TokenType"] = decode_jwt
    #  JWT_TOKEN_FINDER: Callable[[Union["HttpRequest", dict]], Optional[str]] = token_finder
    JWT_EXPIRATION_DELTA=timedelta(minutes=5),
    JWT_LONG_RUNNING_REFRESH_TOKEN=True,
    JWT_REFRESH_TOKEN_N_BYTES=20,
    JWT_REFRESH_EXPIRATION_DELTA=timedelta(days=7),
)
```

**Comment by shmoon-kr** [comment]
I also check PyJWT version.

PyJWT==2.8.0

**Comment by shmoon-kr** [comment]
Here's one more hint.

I tried to print payload of a token when it is created.

The following is a part of `create_token_type(user: "AbstractBaseUser") -> "TokenType":` function.

```
import json
from keewi.models import User
from gqlauth.core.utils import app_settings
from gqlauth.jwt.types_ import TokenPayloadType, TokenType

user = User.objects.get(id=1)

user_pk = app_settings.JWT_PAYLOAD_PK.python_name
pk_field = {user_pk: getattr(user, user_pk)}
payload = TokenPayloadType(
    **pk_field,
)
serialized = json.dumps(payload.as_dict(), sort_keys=True, indent=1)
print("payload", serialized)
```

And the result was

```
payload {
 "exp": "2024-07-31T00:27:30.063228",
 "id": 1,
 "origIat": "2024-07-31T00:22:30.063228"
}
```

Note that the exp and origiIat timestamp in the payload is naive timestamps.
So, what's happening is.

1. A JWT contains native timestamp in its payload.
2. The the token it decoded, it's still a naive timestamp.
3. When it is compared with utc_now() an error is raised since it's comparison between naive timestamp and aware timestamp.

Please review the case.

**Comment by nrbnlulu** [comment]
> This is a part of my requirements.txt file.
> 
> ```
> strawberry-graphql[channels,debug-server]==0.237.1
> strawberry-graphql-django==0.47.1
> strawberry-django-auth==0.377.0
> ```
> 
> and this is a part of my settings.py
> 
> ```
> GQL_AUTH = GqlAuthSettings(
>     ALLOW_LOGIN_NOT_VERIFIED=True,
>     LOGIN_FIELDS={username_field, password_field},
>     LOGIN_REQUIRE_CAPTCHA=False,
>     REGISTER_MUTATION_FIELDS={username_field},
>     REGISTER_REQUIRE_CAPTCHA=False,
>     CAPTCHA_EXPIRATION_DELTA=timedelta(seconds=120),
>     CAPTCHA_MAX_RETRIES=5,
>     # CAPTCHA_TEXT_FACTORY=default_text_factory,
>     # CAPTCHA_TEXT_VALIDATOR=default_captcha_text_validator,
>     FORCE_SHOW_CAPTCHA=False,
>     CAPTCHA_SAVE_IMAGE=False,
>     UPDATE_MUTATION_FIELDS={},
> 
>     # email tokens
>     EXPIRATION_ACTIVATION_TOKEN=timedelta(days=7),
>     EXPIRATION_PASSWORD_RESET_TOKEN=timedelta(hours=1),
>     EXPIRATION_PASSWORD_SET_TOKEN=timedelta(hours=1),
> 
>     # email stuff
>     #EMAIL_FROM: DjangoSetting[str] = DjangoSetting("DEFAULT_FROM_EMAIL")
>     SEND_ACTIVATION_EMAIL=True,
>     ACTIVATION_PATH_ON_EMAIL="activate",
>     PASSWORD_SET_PATH_ON_EMAIL="password-set",
>     PASSWORD_RESET_PATH_ON_EMAIL="password-reset",
> 
>     # email subjects templates
>     EMAIL_SUBJECT_ACTIVATION="email/activation_subject.txt",
>     EMAIL_SUBJECT_ACTIVATION_RESEND="email/activation_subject.txt",
>     EMAIL_SUBJECT_PASSWORD_SET="email/password_set_subject.txt",
>     EMAIL_SUBJECT_PASSWORD_RESET="email/password_reset_subject.txt",
> 
>     # email templates
>     EMAIL_TEMPLATE_ACTIVATION="email/activation_email.html",
>     EMAIL_TEMPLATE_ACTIVATION_RESEND="email/activation_email.html",
>     EMAIL_TEMPLATE_PASSWORD_SET="email/password_set_email.html",
>     EMAIL_TEMPLATE_PASSWORD_RESET="email/password_reset_email.html",
>     #EMAIL_TEMPLATE_VARIABLES=field(default_factory=lambda: {}),
> 
>     # others
>     ALLOW_DELETE_ACCOUNT=False,
>     ALLOW_PASSWORDLESS_REGISTRATION=False,
>     SEND_PASSWORD_SET_EMAIL=False,
> 
>     # JWT stuff
>     #  JWT_SECRET_KEY=DjangoSetting("SECRET_KEY")
>     JWT_ALGORITHM="HS256",
>     JWT_TIME_FORMAT="%Y-%m-%dT%H:%M:%S.%f",
>     #  JWT_PAYLOAD_HANDLER: Callable[["UserProto"], "TokenType"] = create_token_type
>     JWT_PAYLOAD_PK=id_field,
>     #  JWT_DECODE_HANDLER: Callable[[str], "TokenType"] = decode_jwt
>     #  JWT_TOKEN_FINDER: Callable[[Union["HttpRequest", dict]], Optional[str]] = token_finder
>     JWT_EXPIRATION_DELTA=timedelta(minutes=5),
>     JWT_LONG_RUNNING_REFRESH_TOKEN=True,
>     JWT_REFRESH_TOKEN_N_BYTES=20,
>     JWT_REFRESH_EXPIRATION_DELTA=timedelta(days=7),
> )
> ```

Your `JWT_TIME_FORMAT` doesn't contain a TZ so its expected to fail. just add a time zone and you should be fine

**Comment by shmoon-kr** [comment]
The issue was resolved by removing by JWT_TIME_FORMAT="%Y-%m-%dT%H:%M:%S.%f" from the settings.
Thanks!
