### ISSUE TITLE
Cannot override the value of `FROM_EMAIL`

### ISSUE THREAD

**Issue by ammar-faifi** [nrbnlulu/strawberry-django-auth#7]
# Prerequisites

* [x] Is it a bug?
* [ ] Is it a new feature?
* [ ] Is it a a question?
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/nrbnlulu/strawberry-django-auth/blob/master/CONTRIBUTING.md) guide.

# Description

first of all, I appreciate your work.
I tried all the ways to override the Django global value of `DEFAULT_FROM_EMAIL` .
but always the `EMAIL_FROM` is `webmaster@localhost` (Django default). I even use `GqlAuthSettings` with value of `EMAIL_FROM`, but it does not work.
after debugging Django can catch the settings but `GqlAuthSettings` only takes the initial value.

btw, I could override the other settings using `GqlAuthSettings`, except for `EMAIL_FROM`

# Steps to Reproduce

try to run `register` query with changing the default `EMAIL_FROM`

## Expected behavior

the value of `EMAIL_FROM` to change 

## Actual behavior

but it does not, as explained above

# Requirements

```
asgiref==3.5.2
backports.cached-property==1.0.1
certifi==2022.5.18.1
charset-normalizer==2.0.12
click==8.1.3
cloudinary==1.29.0
dj-database-url==0.5.0
Django==4.0.5
django-admin-display==1.3.0
django-cors-headers==3.13.0
django-debug-toolbar==3.4.0
django-filter==21.1
Faker==13.13.0
graphql-core==3.2.1
idna==3.3
packaging==21.3
Pillow==9.1.1
Pygments==2.12.0
PyJWT==2.4.0
pyparsing==3.0.9
python-dateutil==2.8.2
python-multipart==0.0.5
requests==2.28.0
six==1.16.0
sqlparse==0.4.2
strawberry-django-auth==0.3.2
strawberry-django-jwt==0.2.0
strawberry-graphql==0.114.1
strawberry-graphql-django==0.3
typing_extensions==4.2.0
urllib3==1.26.9

```

**Comment by nrbnlulu** [comment]
Hey, have you managed to solve this issue?

**Comment by ammar-faifi** [comment]
Yes, by hard-coding the `EMAIL_FROM='ss@dfg.com'` in `GqlAuthSettings`

but without doing this it won't work, even if there is an explicit value for `DEFAULT_FROM_EMAIL` in `settings.py`
also `EMAIL_FROM= DEFAULT_FROM_EMAIL` won't work

**Comment by nrbnlulu** [comment]
Thanks for reporting i will look in to it  thursday

**Comment by nrbnlulu** [comment]
can you post your relevant  code from settings.py?

**Comment by ammar-faifi** [comment]
some relevant settings 

```python
EMAIL_HOST = 'mail.privateemail.com'
EMAIL_HOST_USER = 'support@cccc.com'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_PORT = 465
EMAIL_USE_SSL = True

AUTHENTICATION_BACKENDS = [
    "gqlauth.backends.GraphQLAuthBackend",
    'django.contrib.auth.backends.ModelBackend',
]



GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": True,
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
    'JWT_EXPIRATION_DELTA': timedelta(minutes=60*24),
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=7),
    # 'JWT_ALLOW_ARGUMENT': True,
    "JWT_ALLOW_ANY_CLASSES": [
        "gqlauth.user.arg_mutations.Register",
        "gqlauth.user.arg_mutations.VerifyAccount",
        "gqlauth.user.arg_mutations.ResendActivationEmail",
        "gqlauth.user.arg_mutations.SendPasswordResetEmail",
        "gqlauth.user.arg_mutations.PasswordReset",
        "gqlauth.user.arg_mutations.ObtainJSONWebToken",
        "gqlauth.user.arg_mutations.VerifyToken",
        "gqlauth.user.arg_mutations.RefreshToken",
        "gqlauth.user.arg_mutations.RevokeToken",
        "gqlauth.user.arg_mutations.VerifySecondaryEmail",
    ],
}

GQL_AUTH = GqlAuthSettings(
    LOGIN_REQUIRED_FIELDS = ['username', 'password'],
    ALLOW_LOGIN_NOT_VERIFIED = False,
    LOGIN_REQUIRE_CAPTCHA = False,
    REGISTER_REQUIRE_CAPTCHA=False,
    # EMAIL_FROM="support@petroly.co",
    ACTIVATION_PATH_ON_EMAIL="confirm",
    EMAIL_TEMPLATE_VARIABLES={
        'frontend_domain': 'petroly.co'
    },
)

```

**Comment by nrbnlulu** [comment]
Please make sure that this is solved with the new release

**Comment by ammar-faifi** [comment]
Great job, it did solve it.

appreciate that.
