### ISSUE TITLE
Unable to query the authenticated user

### ISSUE THREAD

**Issue by JustStanix** [nrbnlulu/strawberry-django-auth#9]
# Prerequisites

* [x] Is it a bug?
* [ ] Is it a new feature?
* [ ] Is it a a question?
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/nrbnlulu/strawberry-django-auth/blob/master/CONTRIBUTING.md) guide.

# Description

We decided to move over to Django 4.0 and that included replacing Graphene, we decided on using Strawberry and came across this package which seemed very useful. Followed the quickstart doc twice and every time the user queries are failing with "unauthenticated".

# Steps to Reproduce

1. `git clone git@github.com:JustStanix/strawberry-django-auth-example.git`
2. Create a new account with register mutation
3. Verify the newly created account with verifyAccount mutation
4. Obtain a JSON Web Token with tokenAuth mutation
5. Run the me query with the Authorization header and the token from tokenAuth()

## Expected behavior

Me query uses the access token and returns information about the authenticated user

## Actual behavior

Receive an "unauthenticated" error code.

# Requirements

asgiref==3.5.2
backports.cached-property==1.0.2
black==22.3.0
click==8.1.3
Django==4.0.5
django-admin-display==1.3.0
Faker==13.13.0
graphql-core==3.2.1
mypy-extensions==0.4.3
packaging==21.3
pathspec==0.9.0
Pillow==9.1.1
platformdirs==2.5.2
Pygments==2.12.0
PyJWT==2.4.0
pyparsing==3.0.9
python-dateutil==2.8.2
python-multipart==0.0.5
six==1.16.0
sqlparse==0.4.2
strawberry-django-auth==0.3.2.1
strawberry-django-jwt==0.2.0
strawberry-graphql==0.114.2
strawberry-graphql-django==0.3
tomli==2.0.1
typing_extensions==4.2.0

**Comment by nrbnlulu** [comment]
Hey, glad you have found this project usefull, I will look in to youre problme tommorrow hopefully, some quastions though.

- Are you using graphiQL in browser? Because as far as i know it dosnt cache youre logged in state.

- you utilized captcha?

- do you require email verification in settigns?

**Comment by nrbnlulu** [comment]
Hey it seems that i cant clone your repo, can you fix that? 
Also i advice you to clone this repo and start the [quickstart](https://github.com/nrbnlulu/strawberry-django-auth/blob/64cfad3632a9b3852fd10e62cbba0ec5341e1cb8/Makefile#L12) and play around with it to see if you still have that bug...

**Comment by nrbnlulu** [comment]
Its seems that i have forgotten to add in the docs  that you have to add Jwt middleware in your schema

**Comment by nrbnlulu** [comment]
Please make sure that this solves your problem
