### ISSUE TITLE
"'ObtainJSONWebTokenInput' object has no attribute 'email'"

### ISSUE THREAD

**Issue by Schulzjo** [nrbnlulu/strawberry-django-auth#96]
Hey,

I actually try to migrate a small project from graphene to strawberry.

On Login Mutation (tokenAuth) I get this error: `"'ObtainJSONWebTokenInput' object has no attribute 'email'"`

Any idea what I am doing wrong?

The registration mutation works fine.

Thx in advance

**Comment by Schulzjo** [comment]
was able to figure it out, was a wrong definition of USERNAME_FIELD in my user model

**Comment by muhammadfaruq72** [comment]
> was able to figure it out, was a wrong definition of USERNAME_FIELD in my user model

I replaced USER_MODEL.USERNAME_FIELD to "username" and it works.

```
#gqlauth/jwt/types_.py

args = {
            USER_MODEL.USERNAME_FIELD: getattr(input_, "username"),
            "password": input_.password,
        }
```

And in my models. These are the setting.

```
USERNAME_FIELD = "email"
EMAIL_FIELD = "email"
```
